import { useEffect, useState } from "react";
import { Home, Newspaper, Megaphone, CalendarDays, Trophy, Users, GraduationCap, Library, BrainCircuit, UserCircle, Settings, LogOut, Menu, Plus, Search, Bot, School, X, ShieldCheck } from "lucide-react";
import { api } from "../services/api";
import Modal from "../components/Modal";

const nav=[["home","Bosh sahifa",Home],["news","Yangiliklar",Newspaper],["announcements","E’lonlar",Megaphone],["events","Tadbirlar",CalendarDays],["achievements","Yutuqlar",Trophy],["teachers","O‘qituvchilar",Users],["students","O‘quvchilar",GraduationCap],["library","Kutubxona",Library],["ai","School AI",BrainCircuit],["profile","Profil",UserCircle]];

export default function Dashboard({user,onLogout}) {
  const [page,setPage]=useState("home"),[mobile,setMobile]=useState(false),[news,setNews]=useState([]),[events,setEvents]=useState([]),[ann,setAnn]=useState([]),[ach,setAch]=useState([]),[schools,setSchools]=useState([]),[users,setUsers]=useState([]),[toast,setToast]=useState(null),[modal,setModal]=useState(null);
  const [newsForm,setNewsForm]=useState({title:"",description:"",image:""});
  const [userForm,setUserForm]=useState({firstName:"",lastName:"",username:"",password:"",role:"TEACHER",schoolId:user.schoolId||""});
  const [aiMsg,setAiMsg]=useState(""),[aiBusy,setAiBusy]=useState(false),[messages,setMessages]=useState([]);
  const isAdmin=user.role==="SUPERADMIN", canWrite=["SUPERADMIN","DIRECTOR","TEACHER"].includes(user.role);
  const notify=(message,type="success")=>{setToast({message,type});setTimeout(()=>setToast(null),2600)};
  const load=async()=>{try{const [n,e,a,g]=await Promise.all([api.news(),api.events(),api.announcements(),api.achievements()]);setNews(n.news||[]);setEvents(e.events||[]);setAnn(a.announcements||[]);setAch(g.achievements||[]);if(isAdmin){setSchools((await api.schools()).schools||[]);setUsers((await api.users()).users||[]);}}catch(e){notify(e.message,"error")}};
  useEffect(()=>{load()},[]);
  const createNews=async e=>{e.preventDefault();try{await api.createNews(newsForm);setModal(null);setNewsForm({title:"",description:"",image:""});notify("Yangi yangilik qo‘shildi");load()}catch(e){notify(e.message,"error")}};
  const deleteNews=async id=>{try{await api.deleteNews(id);notify("Yangilik o‘chirildi");load()}catch(e){notify(e.message,"error")}};
  const createUser=async e=>{e.preventDefault();try{await api.createUser(userForm);setModal(null);notify("Akkaunt muvaffaqiyatli yaratildi");load()}catch(e){notify(e.message,"error")}};
  const askAI=async e=>{e.preventDefault();if(!aiMsg.trim())return;const q=aiMsg;setMessages(m=>[...m,{role:"user",text:q}]);setAiMsg("");setAiBusy(true);try{const x=await api.ai(q);setMessages(m=>[...m,{role:"assistant",text:x.answer}]);notify("AI javobi tayyor")}catch(e){notify(e.message,"error")}finally{setAiBusy(false)}};
  const stats=[["Yangiliklar",news.length,Newspaper],["Tadbirlar",events.length,CalendarDays],["Yutuqlar",ach.length,Trophy],["O‘qituvchilar",users.filter(x=>x.role==="TEACHER").length||"—",Users],["O‘quvchilar",users.filter(x=>x.role==="STUDENT").length||"—",GraduationCap]];
  const content=()=>{
    if(page==="home") return <><div className="welcome"><div><span className="eyebrow">DASHBOARD</span><h1>Assalomu alaykum, {user.firstName}!</h1><p>{user.schoolName||"School AI"} — ta’lim boshqaruvi bir joyda.</p></div><div className="date-pill"><ShieldCheck size={17}/> Tizim himoyalangan</div></div><div className="stats">{stats.map(([n,v,I])=><div className="stat-card" key={n}><div className="stat-icon"><I/></div><span>{n}</span><b>{v}</b></div>)}</div><section className="section"><div className="section-head"><h2>Yaqindagi yangiliklar</h2>{canWrite&&<button className="small-btn" onClick={()=>setModal("news")}><Plus size={16}/> Yangilik</button>}</div><NewsGrid news={news.slice(0,6)} user={user} onDelete={deleteNews}/></section></>;
    if(page==="news") return <Page title="Yangiliklar" sub="Maktabdagi so‘nggi yangiliklar" action={canWrite&&<button className="primary-btn" onClick={()=>setModal("news")}><Plus size={17}/> Yangilik qo‘shish</button>}><NewsGrid news={news} user={user} onDelete={deleteNews}/></Page>;
    if(page==="events") return <Page title="Tadbirlar" sub="Maktab tadbirlari va rejalari"><CardList items={events} icon={CalendarDays} empty="Hozircha tadbirlar yo‘q."/></Page>;
    if(page==="announcements") return <Page title="E’lonlar" sub="Muhim maktab xabarlari"><CardList items={ann} icon={Megaphone} empty="Hozircha e’lonlar yo‘q."/></Page>;
    if(page==="achievements") return <Page title="Yutuqlar" sub="O‘quvchi va maktab yutuqlari"><CardList items={ach} icon={Trophy} empty="Hozircha yutuqlar yo‘q."/></Page>;
    if(page==="teachers"||page==="students") return <Page title={page==="teachers"?"O‘qituvchilar":"O‘quvchilar"} sub="Maktab jamoasi"><div className="table-wrap"><table><thead><tr><th>Ism</th><th>Login</th><th>Rol</th><th>Maktab</th></tr></thead><tbody>{users.filter(x=>page==="teachers"?x.role==="TEACHER":x.role==="STUDENT").map(x=><tr key={x.id}><td>{x.firstName} {x.lastName}</td><td>{x.username}</td><td>{x.role}</td><td>{x.schoolName}</td></tr>)}</tbody></table></div></Page>;
    if(page==="library") return <Page title="Kutubxona" sub="Elektron ta’lim resurslari"><div className="empty-card"><Library size={40}/><h3>Elektron kutubxona</h3><p>Materiallar uchun yagona markaz. Fayl va havolalarni keyingi bosqichda shu yerga biriktirish mumkin.</p></div></Page>;
    if(page==="ai") return <Page title="School AI" sub="Sizning ta’lim yordamchingiz"><div className="ai-box"><div className="ai-messages">{messages.length===0&&<div className="ai-empty"><Bot size={48}/><h3>Bugun nimani o‘rganamiz?</h3><p>Masalan: “8-sinf uchun matematika dars rejasini tuzib ber.”</p></div>}{messages.map((m,i)=><div className={`msg ${m.role}`} key={i}><span>{m.role==="user"?"Siz":"School AI"}</span><p>{m.text}</p></div>)}{aiBusy&&<div className="msg assistant"><span>School AI</span><p className="typing">Javob tayyorlanmoqda...</p></div>}</div><form className="ai-input" onSubmit={askAI}><input value={aiMsg} onChange={e=>setAiMsg(e.target.value)} placeholder="Savolingizni yozing..."/><button className="primary-btn">Yuborish</button></form></div></Page>;
    if(page==="profile") return <Page title="Profil" sub="Shaxsiy ma’lumotlar"><div className="profile-card"><div className="avatar">{user.firstName?.[0]}</div><div><h2>{user.firstName} {user.lastName}</h2><p>{user.username} · {user.role}</p><p>{user.schoolName||"Maktab belgilanmagan"}</p></div></div></Page>;
    if(page==="admin") return <Admin schools={schools} users={users} onAddUser={()=>setModal("user")} onAddSchool={()=>setModal("school")}/>;
  };
  return <div className="app-shell"><aside className={`sidebar ${mobile?"open":""}`}><div className="side-brand"><span className="brand-mark">S</span><b>School AI</b><button className="close-mobile" onClick={()=>setMobile(false)}><X/></button></div><div className="side-nav">{nav.map(([id,label,I])=><button className={page===id?"active":""} key={id} onClick={()=>{setPage(id);setMobile(false)}}><I size={18}/>{label}</button>)}{isAdmin&&<button className={page==="admin"?"active":""} onClick={()=>{setPage("admin");setMobile(false)}}><ShieldCheck size={18}/>Admin Panel</button>}</div><div className="side-bottom"><button><Settings size={18}/>Sozlamalar</button><button onClick={onLogout}><LogOut size={18}/>Chiqish</button></div></aside><main className="main"><header className="topbar"><button className="menu-btn" onClick={()=>setMobile(true)}><Menu/></button><div className="search"><Search size={17}/><span>Qidirish...</span></div><div className="user-mini"><div className="avatar sm">{user.firstName?.[0]}</div><div><b>{user.firstName} {user.lastName}</b><small>{user.role}</small></div></div></header><div className="content">{content()}</div></main><Toast toast={toast}/><Modal open={modal==="news"} title="Yangi yangilik" onClose={()=>setModal(null)}><form className="form" onSubmit={createNews}><label>Sarlavha<input required value={newsForm.title} onChange={e=>setNewsForm({...newsForm,title:e.target.value})}/></label><label>Tavsif<textarea required value={newsForm.description} onChange={e=>setNewsForm({...newsForm,description:e.target.value})}/></label><label>Rasm URL<input value={newsForm.image} onChange={e=>setNewsForm({...newsForm,image:e.target.value})}/></label><button className="primary-btn full">Saqlash</button></form></Modal><Modal open={modal==="user"} title="Foydalanuvchi yaratish" onClose={()=>setModal(null)}><form className="form" onSubmit={createUser}><label>Ism<input required value={userForm.firstName} onChange={e=>setUserForm({...userForm,firstName:e.target.value})}/></label><label>Familiya<input required value={userForm.lastName} onChange={e=>setUserForm({...userForm,lastName:e.target.value})}/></label><label>Login<input required value={userForm.username} onChange={e=>setUserForm({...userForm,username:e.target.value})}/></label><label>Parol<input required type="password" value={userForm.password} onChange={e=>setUserForm({...userForm,password:e.target.value})}/></label><label>Rol<select value={userForm.role} onChange={e=>setUserForm({...userForm,role:e.target.value})}><option>DIRECTOR</option><option>TEACHER</option><option>STUDENT</option><option>PARENT</option></select></label><button className="primary-btn full">Akkaunt yaratish</button></form></Modal><Modal open={modal==="school"} title="Maktab yaratish" onClose={()=>setModal(null)}><SchoolForm onDone={()=>{setModal(null);load();notify("Maktab yaratildi")}}/></Modal></div>
}
function Page({title,sub,action,children}){return <><div className="page-title"><div><span className="eyebrow">SCHOOL AI</span><h1>{title}</h1><p>{sub}</p></div>{action}</div>{children}</>}
function NewsGrid({news,user,onDelete}){return <div className="news-grid">{news.map(n=><article className="news-card" key={n.id}>{n.image&&<img src={n.image} onError={e=>e.currentTarget.style.display="none"}/>}<div className="news-body"><small>{new Date(n.createdAt).toLocaleDateString("uz-UZ")} · {n.authorName}</small><h3>{n.title}</h3><p>{n.description}</p>{(user.role==="SUPERADMIN"||user.role==="DIRECTOR"||n.authorId===user.id)&&<button className="text-btn" onClick={()=>onDelete(n.id)}>O‘chirish</button>}</div></article>)}{!news.length&&<div className="empty-card">Hozircha yangiliklar mavjud emas.</div>}</div>}
function CardList({items,icon:Icon,empty}){return <div className="list-grid">{items.map(x=><div className="list-card" key={x.id}><Icon/><div><small>{x.createdAt&&new Date(x.createdAt).toLocaleDateString("uz-UZ")}</small><h3>{x.title||x.name}</h3><p>{x.description||x.content}</p></div></div>)}{!items.length&&<div className="empty-card">{empty}</div>}</div>}
function Admin({schools,users,onAddUser,onAddSchool}){return <><div className="page-title"><div><span className="eyebrow">SUPERADMIN</span><h1>Admin Panel</h1><p>Barcha maktab va foydalanuvchilar boshqaruvi.</p></div></div><div className="admin-grid"><div className="admin-card"><div className="section-head"><h2>Maktablar</h2><button className="small-btn" onClick={onAddSchool}><Plus size={15}/> Maktab</button></div>{schools.map(s=><div className="admin-row" key={s.id}><School size={18}/><span><b>{s.name}</b><small>{s.region}, {s.district}</small></span></div>)}</div><div className="admin-card"><div className="section-head"><h2>Foydalanuvchilar</h2><button className="small-btn" onClick={onAddUser}><Plus size={15}/> Akkaunt</button></div>{users.map(s=><div className="admin-row" key={s.id}><UserCircle size={18}/><span><b>{s.firstName} {s.lastName}</b><small>{s.username} · {s.role}</small></span></div>)}</div></div></>}
function SchoolForm({onDone}){const [f,setF]=useState({name:"",region:"",district:"",address:"",phone:"",logo:""});const submit=async e=>{e.preventDefault();try{await api.createSchool(f);onDone()}catch(e){alert(e.message)}};return <form className="form" onSubmit={submit}><label>Maktab nomi<input required value={f.name} onChange={e=>setF({...f,name:e.target.value})}/></label><label>Viloyat<input value={f.region} onChange={e=>setF({...f,region:e.target.value})}/></label><label>Tuman/shahar<input value={f.district} onChange={e=>setF({...f,district:e.target.value})}/></label><label>Manzil<input value={f.address} onChange={e=>setF({...f,address:e.target.value})}/></label><label>Telefon<input value={f.phone} onChange={e=>setF({...f,phone:e.target.value})}/></label><label>Logo URL<input value={f.logo} onChange={e=>setF({...f,logo:e.target.value})}/></label><button className="primary-btn full">Maktab yaratish</button></form>}
